---
# vars file for openstack.servers
openstack_server: []

os_server:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}

os_networks:
  # Public Facing Network   
  external:
    cloud_name: openstack
    network_name: ext_network
    subnet_name: ext_subnet
    cidr_network: "192.0.2.0/24"
    state: present
    external: true


  # Private Facing Network   
  internal:
    cloud_name: openstack
    network_name: int_network
    subnet_name: int_subnet
    cidr_network: "172.16.0.0/24"
    state: present
    external: false

  # Public Facing Router connecting the two networks
os_router:
  router:
    cloud_name: openstack
    state: present
    name: router
    network: ext_network
    interface: int_subnet

...
